#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    disable-test.sh                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gfielder <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/24 16:59:12 by gfielder          #+#    #+#              #
#    Updated: 2019/03/24 16:59:12 by gfielder         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILENAME=unit_tests.c

if [ $# -eq 0 ]
then
	PATTERN=""
elif [ $# -ne 1 ]
then
	echo "usage: ./disable-test  search-pattern"
	echo "       search patterns are a single word, using * for wildcards. (Enclose in double quotes if using *, or escape the * eg \\*)"
	exit 1
else
	PATTERN=$(echo $1 | tr -d " \t\r\n")
fi

TOREGEX=$(echo $PATTERN | sed "s/[^a-zA-Z0-9_]/.\*/g")
NUM_DISABLED=$(grep -c "^int[	 ]*$TOREGEX.*(void)" $FILENAME | tr -d " \t\r\n")

if [ $NUM_DISABLED -eq 0 ]
then
	echo "No enabled tests were found that match the pattern \"$PATTERN*\"."
	exit 0
fi

sed -i .bak "s/^int[	 ]*$TOREGEX.*(void)/ &/g" $FILENAME
echo "Disabled $NUM_DISABLED tests matching the pattern \"$PATTERN*\"."

if [ $? -eq 0 ]
then
	rm $FILENAME.bak
	make -C $(dirname $0) fclean
else
 	echo "Error occurred while performing sed operation. If any changes were made, the unit test file has been backed up to $FILENAME.bak. Please check your input and try again."
fi
