#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    disable-test.sh                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gfielder <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/24 16:59:12 by gfielder          #+#    #+#              #
#    Updated: 2019/03/24 16:59:12 by gfielder         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

if [ $# -ne 1 ]
then
	echo "usage: ./disable-test  test-prefix"
	exit 1
fi

FILENAME=unit_tests.c


# Treat the argument as test-prefix and perform a name-based search
PREFIX=$(echo $1 | tr -d " \t\r\n")
NUM_DISABLED=$(grep -c "^int[	 ]*$PREFIX.*(void)" $FILENAME | tr -d " \t\r\n")

if [ $NUM_DISABLED -eq 0 ]
then
	echo "No enabled tests were found that start with \"$PREFIX\"."
	exit 0
fi

echo "Disabling tests that start with \"$PREFIX\"..."

sed -i .bak "s/^int[	 ]*$PREFIX.*(void)/ &/g" $FILENAME
echo "Disabled $NUM_DISABLED tests that start with \"$PREFIX\"."

if [ $? -eq 0 ]
then
	rm $FILENAME.bak
	make -C $(dirname $0) fclean
else
 	echo "Error occurred while performing prefix-based sed operation. If any changes were made, the unit test file has been backed up to $FILENAME.bak. Please check your input and try again."
fi
