#!/bin/sh
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    enable-test.sh                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gfielder <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/24 16:59:12 by gfielder          #+#    #+#              #
#    Updated: 2019/03/24 16:59:12 by gfielder         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

if [ $# -ne 1 ]
then
	echo "usage: ./enable-test  test-prefix"
	exit 1
fi

FILENAME=unit_tests.c

PREFIX=$(echo $1 | tr -d " \t\r\n")
NUM_ENABLED=$(grep -c "^[	 ]*int[	 ]*$PREFIX.*(void)" $FILENAME | tr -d " \t\r\n")

if [ $NUM_ENABLED -eq 0 ]
then
	echo "No disabled tests were found that start with \"$PREFIX\"."
	exit 0
fi

sed -i .bak "s/^[	 ]*\(int[	 ]*$PREFIX.*(void)\)/\1/g" $FILENAME
echo "Enabled $NUM_ENABLED tests that start with \"$PREFIX\"."

if [ $? -eq 0 ]
then
	rm $FILENAME.bak
	make -C $(dirname $0) fclean
else
 	echo "Error occurred while performing prefix-based sed operation. If any changes were made, the unit test file has been backed up to $FILENAME.bak. Please check your input and try again."
fi
