#!/bin/sh

PFT_ROOT="$(dirname $0)/../.."

# Default configuration
$PFT_ROOT/enable-test -q 
$PFT_ROOT/disable-test -q "*notmandatory" 
$PFT_ROOT/disable-test -q "argnum"
$PFT_ROOT/disable-test -q "f_*reserved_values" 
$PFT_ROOT/disable-test -q "*undefbehav" 
$PFT_ROOT/enable-test -q "*_mandatory_*undefbehav"
$PFT_ROOT/disable-test -q "*dblmax" 

# 'NOT TESTED' under the minimal specification
$PFT_ROOT/disable-test -q "pct_*w" 
$PFT_ROOT/disable-test -q "pct_*lj" 

$PFT_ROOT/disable-test -q "d_*as*size" 
$PFT_ROOT/disable-test -q "d_*size*as" 
$PFT_ROOT/disable-test -q "i_*as*size" 
$PFT_ROOT/disable-test -q "i_*size*as" 
$PFT_ROOT/disable-test -q "d_*sp*size" 
$PFT_ROOT/disable-test -q "d_*size*sp" 
$PFT_ROOT/disable-test -q "i_*sp*size" 
$PFT_ROOT/disable-test -q "i_*size*sp" 
$PFT_ROOT/disable-test -q "d_*sp*zp" 
$PFT_ROOT/disable-test -q "d_*zp*sp" 
$PFT_ROOT/disable-test -q "i_*sp*zp" 
$PFT_ROOT/disable-test -q "i_*zp*sp" 
$PFT_ROOT/disable-test -q "d_*as*zp" 
$PFT_ROOT/disable-test -q "d_*zp*as" 
$PFT_ROOT/disable-test -q "i_*as*zp" 
$PFT_ROOT/disable-test -q "i_*zp*as" 
$PFT_ROOT/disable-test -q "d_*size*zp" 
$PFT_ROOT/disable-test -q "d_*zp*size" 
$PFT_ROOT/disable-test -q "i_*size*zp" 
$PFT_ROOT/disable-test -q "i_*zp*size" 

$PFT_ROOT/disable-test -q "o_*zp*size" 
$PFT_ROOT/disable-test -q "o_*size*zp" 
$PFT_ROOT/disable-test -q "o_*zp*af" 
$PFT_ROOT/disable-test -q "o_*af*zp" 
$PFT_ROOT/disable-test -q "o_*af*prec" 
$PFT_ROOT/disable-test -q "o_*prec*af" 
$PFT_ROOT/disable-test -q "o_*size*af" 
$PFT_ROOT/disable-test -q "o_*af*size" 

$PFT_ROOT/disable-test -q "u_*zp*size" 
$PFT_ROOT/disable-test -q "u_*size*zp" 

$PFT_ROOT/disable-test -q "x_*zp*size" 
$PFT_ROOT/disable-test -q "x_*size*zp" 
$PFT_ROOT/disable-test -q "x_*af*size" 
$PFT_ROOT/disable-test -q "x_*size*af"
$PFT_ROOT/disable-test -q "x_*af*prec" 
$PFT_ROOT/disable-test -q "x_*prec*af"
$PFT_ROOT/disable-test -q "x_*af*zp" 
$PFT_ROOT/disable-test -q "x_*zp*af"
$PFT_ROOT/disable-test -q "X_*zp*size" 
$PFT_ROOT/disable-test -q "X_*size*zp" 
$PFT_ROOT/disable-test -q "X_*af*size" 
$PFT_ROOT/disable-test -q "X_*size*af"
$PFT_ROOT/disable-test -q "X_*af*prec" 
$PFT_ROOT/disable-test -q "X_*prec*af"
$PFT_ROOT/disable-test -q "X_*af*zp" 
$PFT_ROOT/disable-test -q "X_*zp*af"

$PFT_ROOT/disable-test -q "f_L*as"
$PFT_ROOT/disable-test -q "f_*size*as"
$PFT_ROOT/disable-test -q "f_*as*size"
$PFT_ROOT/disable-test -q "f_*as*prec"
$PFT_ROOT/disable-test -q "f_*prec*as"
$PFT_ROOT/disable-test -q "f_*af*as"
$PFT_ROOT/disable-test -q "f_*as*af"
$PFT_ROOT/disable-test -q "f_*as*zp"
$PFT_ROOT/disable-test -q "f_*zp*as"
$PFT_ROOT/disable-test -q "f_*sp*size"
$PFT_ROOT/disable-test -q "f_*size*sp"
$PFT_ROOT/disable-test -q "f_L*sp"
$PFT_ROOT/disable-test -q "f_*sp*af"
$PFT_ROOT/disable-test -q "f_*af*sp"
$PFT_ROOT/disable-test -q "f_*sp*zp"
$PFT_ROOT/disable-test -q "f_*zp*sp"
$PFT_ROOT/disable-test -q "f_*zp*size"
$PFT_ROOT/disable-test -q "f_*size*zp"
$PFT_ROOT/disable-test -q "f_*prec*zp"
$PFT_ROOT/disable-test -q "f_*zp*prec"
$PFT_ROOT/disable-test -q "f_*zp*af"
$PFT_ROOT/disable-test -q "f_*af*zp"
$PFT_ROOT/disable-test -q "f_*af*w"
$PFT_ROOT/disable-test -q "f_*w*af"
$PFT_ROOT/disable-test -q "f_*af*lj"
$PFT_ROOT/disable-test -q "f_*lj*af"

$PFT_ROOT/disable-test -q "f_*prec9"
$PFT_ROOT/disable-test -q "f_*prec10"
$PFT_ROOT/disable-test -q "f_*prec11"
$PFT_ROOT/disable-test -q "f_*prec12"
$PFT_ROOT/disable-test -q "f_*prec13"
$PFT_ROOT/disable-test -q "f_*prec14"
$PFT_ROOT/disable-test -q "f_*prec15"
$PFT_ROOT/disable-test -q "f_*prec16"
$PFT_ROOT/disable-test -q "f_*prec17"
$PFT_ROOT/disable-test -q "f_*prec18"
$PFT_ROOT/disable-test -q "f_*prec19"
$PFT_ROOT/disable-test -q "f_*prec20"
$PFT_ROOT/disable-test -q "f_*prec21"
$PFT_ROOT/disable-test -q "f_*prec22"
$PFT_ROOT/disable-test -q "f_*reserved_values"

make -C $PFT_ROOT fclean
